from .Bishop import Bishop
from .Knight import Knight
from .Pawn import Pawn
from .Rook import Rook


class BoardConfig:

    @staticmethod
    def getPieceConfigs():
        return [
            {
                "class": Rook,
                "fileName": "rook_black",
                "playerName": "Player2",
                "objectName": "rook_0",
                "space": 0,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_1",
                "space": 1,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Bishop,
                "fileName": "bishop_black",
                "playerName": "Player2",
                "objectName": "bishop_2",
                "space": 2,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_3",
                "space": 3,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_4",
                "space": 4,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Bishop,
                "fileName": "bishop_black",
                "playerName": "Player2",
                "objectName": "bishop_5",
                "space": 5,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_6",
                "space": 6,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Rook,
                "fileName": "rook_black",
                "playerName": "Player2",
                "objectName": "rook_7",
                "space": 7,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_8",
                "space": 8,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_9",
                "space": 9,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_10",
                "space": 10,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_11",
                "space": 11,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_12",
                "space": 12,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_13",
                "space": 13,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_14",
                "space": 14,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_black",
                "playerName": "Player2",
                "objectName": "pawn_15",
                "space": 15,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Rook,
                "fileName": "rook_white",
                "playerName": "Player1",
                "objectName": "rook_63",
                "space": 63,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_62",
                "space": 62,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Bishop,
                "fileName": "bishop_white",
                "playerName": "Player1",
                "objectName": "bishop_61",
                "space": 61,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_60",
                "space": 60,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_59",
                "space": 59,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Bishop,
                "fileName": "bishop_white",
                "playerName": "Player1",
                "objectName": "bishop_58",
                "space": 58,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_57",
                "space": 57,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Rook,
                "fileName": "rook_white",
                "playerName": "Player1",
                "objectName": "rook_56",
                "space": 56,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_55",
                "space": 55,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_54",
                "space": 54,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "knight_53",
                "space": 53,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_52",
                "space": 52,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_51",
                "space": 51,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_50",
                "space": 50,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_49",
                "space": 49,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Pawn,
                "fileName": "pawn_white",
                "playerName": "Player1",
                "objectName": "pawn_48",
                "space": 48,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
        ]
