class BoardConfigSectionKeys:
    TILES = "tiles"
    KNIGHTS = "knights"
    ROOKS = "rooks"
    PAWNS = "pawns"
    BISHOPS = "bishops"
    QUEENS = "queens"
    KINGS = "kings"
    PLAYERS = "players"
    BOARD = "board"
