from .Knight import Knight


class BoardConfig:

    @staticmethod
    def getPieceConfigs():
        return [
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_0",
                "space": 0,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_1",
                "space": 1,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_2",
                "space": 2,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_3",
                "space": 3,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_4",
                "space": 4,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_5",
                "space": 5,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_6",
                "space": 6,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_7",
                "space": 7,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_8",
                "space": 8,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_9",
                "space": 9,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_10",
                "space": 10,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_11",
                "space": 11,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_12",
                "space": 12,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_13",
                "space": 13,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_14",
                "space": 14,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_black",
                "playerName": "Player2",
                "objectName": "knight_15",
                "space": 15,
                "team": "black",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_63",
                "space": 63,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_62",
                "space": 62,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_61",
                "space": 61,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_60",
                "space": 60,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_59",
                "space": 59,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_58",
                "space": 58,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_57",
                "space": 57,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_56",
                "space": 56,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_55",
                "space": 55,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_54",
                "space": 54,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_53",
                "space": 53,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_52",
                "space": 52,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_51",
                "space": 51,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_50",
                "space": 50,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_49",
                "space": 49,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
            {
                "class": Knight,
                "fileName": "knight_white",
                "playerName": "Player1",
                "objectName": "knight_48",
                "space": 48,
                "team": "white",
                "timesMoved": 0,
                "claimedPieces": 0,
                "isOnBoard": True,
            },
        ]
